apiVersion: rbac.authorization.k8s.io/v1
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:

  name: cf1-role2
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["my-configmap"]
  verbs: ["update", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-grantor-cf2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cf1-role2
subjects:
  - kind: ServiceAccount
    name: test1
    namespace: cf1
